<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Daftar</name>
   <tag></tag>
   <elementGuidId>0d1ec7ff-4fb5-40fd-84c1-b795998b16b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ml-auto.mr-auto.text-center > a.btn.btn-round.btn-rose</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='agrement2()']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6479916f-d28c-4a63-b2e3-f2286b81ca90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#pablo</value>
      <webElementGuid>c28c69b4-0f2e-4154-b474-b5ed332c725b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-round btn-rose</value>
      <webElementGuid>eb693907-5376-4673-a4cd-4b5e43e4d1a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>agrement2()</value>
      <webElementGuid>e3b35e70-4fbf-44e1-8241-d08b6fdf9ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar</value>
      <webElementGuid>5f202824-9ed3-4770-ae57-507901196551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;perfect-scrollbar-on&quot;]/body[@class=&quot;off-canvas-sidebar&quot;]/div[@class=&quot;pricing-page header-filter bag&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;tab_three&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-footer&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-10&quot;]/div[@class=&quot;ml-auto mr-auto text-center&quot;]/a[@class=&quot;btn btn-round btn-rose&quot;]</value>
      <webElementGuid>c1c5af2d-93b6-4cec-a10a-e2d22d582153</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='agrement2()']</value>
      <webElementGuid>dd479523-942b-4f34-81a6-663c0e22a9eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Daftar')]</value>
      <webElementGuid>165f4073-0b7c-4888-8c0c-39740ccde513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mohon centang verifikasi dibawah ini :'])[1]/following::a[1]</value>
      <webElementGuid>96bb6bb2-f928-416d-b172-068e997e90d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih metode Pembayaran'])[1]/following::a[1]</value>
      <webElementGuid>d258a839-34fe-4578-9a4a-26f145d32539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Creative Tim'])[1]/preceding::a[1]</value>
      <webElementGuid>fbd92408-8de6-4a9c-bb3c-f5342af3fd18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Us'])[1]/preceding::a[2]</value>
      <webElementGuid>bd997517-0003-4e31-969a-5c4832f43c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#pablo')])[4]</value>
      <webElementGuid>91b9e4ef-c876-4b6b-8c5a-ec7cf53fb539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>be5effcb-a855-448b-9a39-998b05b7b087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#pablo' and (text() = 'Daftar' or . = 'Daftar')]</value>
      <webElementGuid>f6b1952b-1f0a-4a91-9a3d-592ae4adeba6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
