<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pilih</name>
   <tag></tag>
   <elementGuidId>02b50865-0969-4527-a130-f743eb2fb6c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-round.btn-rose.click_step_three</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;plan('1')&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cc02a0db-b1ce-41ce-82bf-d87e4aa2107b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#pablo</value>
      <webElementGuid>bcb7d1df-7eac-4535-a4b5-9ff932e521e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-round btn-rose click_step_three</value>
      <webElementGuid>bd998ba6-20c2-410e-b6cd-80c873d19ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>plan('1')</value>
      <webElementGuid>562faacf-8ee0-4aa8-a0e9-92665d3464bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih</value>
      <webElementGuid>7d26d52c-b4f9-4488-b1f2-8a5ebda359a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;perfect-scrollbar-on&quot;]/body[@class=&quot;off-canvas-sidebar&quot;]/div[@class=&quot;pricing-page header-filter bag&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;tab_two&quot;]/div[2]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4&quot;]/div[@class=&quot;card card-pricing&quot;]/div[@class=&quot;card-footer justify-content-center&quot;]/a[@class=&quot;btn btn-round btn-rose click_step_three&quot;]</value>
      <webElementGuid>6267a254-162d-4b2b-b62d-0ff1e00be458</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;plan('1')&quot;]</value>
      <webElementGuid>c448265f-5228-4e52-9b8f-87fe33ccb8cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pilih')]</value>
      <webElementGuid>e287b20f-10d7-4614-9903-ee1a5c3fb90c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard dan Leaderboard'])[1]/following::a[1]</value>
      <webElementGuid>fe5e1ec6-733b-42cf-9b76-c922a9fee42c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mutasi dan Tiket'])[1]/following::a[1]</value>
      <webElementGuid>df48b09b-512c-4b88-860e-c55baaa14018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PREMIUM'])[1]/preceding::a[1]</value>
      <webElementGuid>1a0f2cb3-1168-494e-8c20-be8993134e96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp. 250.000'])[1]/preceding::a[1]</value>
      <webElementGuid>89f7f3c0-5d45-4f41-a386-0c757a5ec4d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pilih']/parent::*</value>
      <webElementGuid>cb54b8ed-1953-4648-9927-e598a42f7557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#pablo')])[2]</value>
      <webElementGuid>7ab05341-b40f-422f-9b67-54de9b36f93a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>208f80ad-d731-499c-bd1e-733d87bcc145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#pablo' and (text() = 'Pilih' or . = 'Pilih')]</value>
      <webElementGuid>aa130435-754b-4715-ad29-5f9bdaacec86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
