<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Selanjutnya</name>
   <tag></tag>
   <elementGuidId>492db9af-6bdd-41ba-9f5a-d0e262c6345d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#click_step_one</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='click_step_one']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a92bcebd-c78a-44be-81c5-6f38478e323a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#pablo</value>
      <webElementGuid>e76ac527-2ad5-4b60-acd9-fce91169ee3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-round btn-rose</value>
      <webElementGuid>4d68cac0-2fe4-44f0-a268-e1465df22af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>click_step_one</value>
      <webElementGuid>7e555bcd-f7b9-4664-9ad1-6f7206f82218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selanjutnya</value>
      <webElementGuid>b3b21959-2e93-4006-980a-5e5391d2b47e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;click_step_one&quot;)</value>
      <webElementGuid>e982ceff-459d-4f2f-b3b0-d02b15c37bb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='click_step_one']</value>
      <webElementGuid>66f74115-8f1c-4f5c-b3c5-13df7d0aca5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Selanjutnya')]</value>
      <webElementGuid>eb659d20-1e76-4a4a-b1f5-78e1a3d534f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Whatsapp Untuk Konfirmasi'])[1]/following::a[1]</value>
      <webElementGuid>64f4879a-cbf3-4ff7-9301-455ac2b93bba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ulangi Password'])[1]/following::a[1]</value>
      <webElementGuid>9ca75476-60bf-4572-95ee-8b045c820769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih plan sesuai keinginanmu'])[1]/preceding::a[1]</value>
      <webElementGuid>36a53f36-0490-4234-8742-25cca6a9d40f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plan pilihanmu dapat menentukan fitur apa saja yang akan ada dapat di resellerindo'])[1]/preceding::a[1]</value>
      <webElementGuid>5ee085c4-ad2e-42a9-b711-8b307bbac1f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Selanjutnya']/parent::*</value>
      <webElementGuid>c5d9a17e-3535-42e3-8581-015b0088a5a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#pablo')]</value>
      <webElementGuid>df3f5858-946a-45d1-8dbb-493c065837d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>8c15406b-fd93-42e4-8d08-1a9ca5b18948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#pablo' and @id = 'click_step_one' and (text() = 'Selanjutnya' or . = 'Selanjutnya')]</value>
      <webElementGuid>0d07e66d-3d55-4dbb-8a9c-04fc015df7c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
