<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Mohon centang verifikasi dibawah ini_d0b9b7</name>
   <tag></tag>
   <elementGuidId>ffe36b37-c693-431a-aad6-70789d6cf075</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-5ihe4kf0zpdm&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@title = 'reCAPTCHA' and @name = 'a-5ihe4kf0zpdm' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6Lcv2G8UAAAAAH8Ow1CGqVomiO08P_4ESg0J81uz&amp;co=aHR0cHM6Ly9ycy1kZXYucHJvbW9zaW5kby53ZWIuaWQ6NDQz&amp;hl=en&amp;v=MHBiAvbtvk5Wb2eTZHoP1dUd&amp;size=normal&amp;cb=rc44m9yeqtnr']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-5ihe4kf0zpdm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>c260009b-7a20-43ed-94c8-40d42e817886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>97949425-e599-4929-982a-85cedb1c6cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>2593ec08-7bdf-4307-84e3-901d64cae33d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>7f99094b-6f0c-4469-911b-5f83cb1a593b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>148f97b6-c8bc-4ea1-b718-4b3c3e9e10cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-5ihe4kf0zpdm</value>
      <webElementGuid>a4f643c6-1e8b-4ad7-9a3a-8d8ef99ebe5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7d753a43-b3ff-44f0-acf3-feb2cd37001f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>6fbb14f0-55d4-40d1-b7a8-0abd02a4fe2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>47d80c5f-6260-4718-bbed-355b7abed6a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6Lcv2G8UAAAAAH8Ow1CGqVomiO08P_4ESg0J81uz&amp;co=aHR0cHM6Ly9ycy1kZXYucHJvbW9zaW5kby53ZWIuaWQ6NDQz&amp;hl=en&amp;v=MHBiAvbtvk5Wb2eTZHoP1dUd&amp;size=normal&amp;cb=rc44m9yeqtnr</value>
      <webElementGuid>be4163ee-ea34-45e1-95b6-10ebe469b16c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;perfect-scrollbar-on&quot;]/body[@class=&quot;off-canvas-sidebar&quot;]/div[@class=&quot;pricing-page header-filter bag&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;tab_three&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;card&quot;]/center[1]/div[@class=&quot;g-recaptcha&quot;]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>be774f67-d3a6-4411-b3b0-978c322869f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-5ihe4kf0zpdm']</value>
      <webElementGuid>0c30cc8b-b1dc-490a-b47d-c02d6c9411ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//center/div/div/div/iframe</value>
      <webElementGuid>5ee1d158-72e8-4819-9295-a6522749f27f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-5ihe4kf0zpdm' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6Lcv2G8UAAAAAH8Ow1CGqVomiO08P_4ESg0J81uz&amp;co=aHR0cHM6Ly9ycy1kZXYucHJvbW9zaW5kby53ZWIuaWQ6NDQz&amp;hl=en&amp;v=MHBiAvbtvk5Wb2eTZHoP1dUd&amp;size=normal&amp;cb=rc44m9yeqtnr']</value>
      <webElementGuid>adc27893-ed1e-4872-bb90-5168fb99fbf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
