<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama_first</name>
   <tag></tag>
   <elementGuidId>39a783dc-551e-4d44-ad33-c24343c41ab4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#first</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='first']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2cb50259-824e-45d4-9d9a-6bbc8f41223f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3f7cb72f-a45d-448b-8f03-aa4b67b69e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>first</value>
      <webElementGuid>98d22a6c-6780-4b6f-9b05-abf256941121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama...</value>
      <webElementGuid>3583102f-4459-4fd0-91dc-fba7276ddfed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>first</value>
      <webElementGuid>84230781-c4ae-46f0-82e8-998d6d9ecfa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5338e843-68ee-475e-977f-a814047023f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;first&quot;)</value>
      <webElementGuid>181d8962-5b6e-4813-bf2a-5f9be54d3b93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='first']</value>
      <webElementGuid>c98d3039-1715-4bcc-a1c0-b67c2979be68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>03e720d5-6e72-4fa2-87f0-9191b18b814c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'first' and @placeholder = 'Nama...' and @id = 'first']</value>
      <webElementGuid>5738bc85-616d-46b9-8888-75594d167983</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
