<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kontak Kami_setuju</name>
   <tag></tag>
   <elementGuidId>b174040d-e681-45bc-a0d7-a04e4f95b3c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#setuju</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='setuju']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5cfa7b2d-f23c-4c8f-89d5-f60e59be6b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8a08daa5-bd38-4458-bdee-fb7010f013a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info</value>
      <webElementGuid>57c5202a-9109-48e2-a1a0-3ae24417cdba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ajax_action_register2()</value>
      <webElementGuid>267dcb20-3d5e-44e5-98ae-78863697498d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Setuju</value>
      <webElementGuid>c74880d3-a30d-4729-9d45-5d3d9f6a87d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>setuju</value>
      <webElementGuid>c82e1082-85a0-46d2-97df-90d8da70ec7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;setuju&quot;)</value>
      <webElementGuid>33926499-0aed-49e2-bc3f-243c6866d07c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='setuju']</value>
      <webElementGuid>82dfba09-f198-419c-9246-6dcc39d762b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>bb8a9268-c43a-410c-91e6-39d471253fa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'setuju']</value>
      <webElementGuid>d505013d-8f19-4a7c-aba9-b54a6b68e5fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
