<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ulangi Password_repassword</name>
   <tag></tag>
   <elementGuidId>2d438539-d04b-494e-a51e-06d205fc37e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#repassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='repassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>68a68295-5e09-4a94-bd64-0609575635b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>b811f20b-8b8c-404e-a088-3fb00103232d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>repassword</value>
      <webElementGuid>c73f77f2-a7a6-4d11-a023-ff3e06ad9b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>repassword</value>
      <webElementGuid>d84a3ef7-2e0d-45e9-9d52-4d981ebc874b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>repassword</value>
      <webElementGuid>dab50da1-80d3-4af5-a3bb-4a4d31540321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>33c8253d-057a-407c-a365-9daf16f6dbac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;repassword&quot;)</value>
      <webElementGuid>3a8b962f-5e1f-4173-b4f5-408574039427</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='repassword']</value>
      <webElementGuid>c1307f95-2d1b-4eb1-be88-ef5cf4ab1f02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/span/input</value>
      <webElementGuid>f14138de-0444-4099-909d-69627485ece2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'repassword' and @id = 'repassword' and @placeholder = 'repassword']</value>
      <webElementGuid>833eab03-e9c1-4cf0-b3d0-bc2e44d59627</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
